import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

function dt(month: number, day: number, year = 2026): Date {
  return new Date(year, month - 1, day)
}

type Row = [
  string, // usiaJenisPasien
  string, // namaPasien
  Date,   // tanggalPenilaian
  string, // ruangRawat
  number, number, number, number, number, // T K R W V
  string | null, // keluhanDi
  string | null, // kritikSaran
]

function toSurvey(bulanPenilaian: string, row: Row) {
  const [usiaJenisPasien, namaPasien, tanggalPenilaian, ruangRawat,
    nilaiTampilan, nilaiKebersihan, nilaiRasa, nilaiWaktu, nilaiVariasi,
    keluhanDi, kritikSaran] = row
  return {
    bulanPenilaian,
    usiaJenisPasien,
    namaPasien,
    tanggalPenilaian,
    ruangRawat,
    nilaiTampilan,
    nilaiKebersihan,
    nilaiRasa,
    nilaiWaktu,
    nilaiVariasi,
    keluhanDi: keluhanDi ?? null,
    kritikSaran: kritikSaran ?? null,
  }
}

// ── MARET 2026 ──────────────────────────────────────────────────────────────
const MARET: Row[] = [
  ['Bayi',             'ALLEGRA MARIA LIN STOLFI',                       dt(3,2),  '305',    4,4,4,4,4, 'Makan siang', 'Wortel terlalu banyak, jadi penunggu pasien request wortelnya di berikan dalam jumlah yang sedikit'],
  ['Anak',             'SOFIIA IMPERIDI',                                 dt(3,2),  '202',    4,4,4,4,4, null,          null],
  ['Dewasa',           'I GUSTI AGUNG SATYA DHARMA NINGRUM, SE',          dt(3,2),  '307',    4,4,4,4,4, null,          null],
  ['Dewasa',           'LOTTA LENA ANNA HUIJSMAN',                        dt(3,2),  '306',    5,5,5,5,5, null,          null],
  ['Anak',             'DEWA GEDE DANENDRA ARSYAWIRYA',                   dt(3,5),  '204',    4,4,4,4,4, 'Makan siang', 'Nasi anak agak kering'],
  ['Anak',             'DEWA GEDE DANENDRA ARSYAWIRYA',                   dt(3,5),  '204',    5,5,5,5,5, null,          null],
  ['Dewasa',           'SHANNON ALYCE WALL',                              dt(3,6),  '202',    4,4,4,4,4, 'Makan siang', 'untuk ayam masih ada tulangnya dan agak gosong'],
  ['Dewasa',           'LIANNA KARTIKAWATI',                              dt(3,6),  '305',    5,5,5,5,5, null,          'belum makan siang, karena lagi ingin makan buah. tidak ada keluhan'],
  ['Anak',             'DEWA GEDE DANENDRA ARSYAWIRYA',                   dt(3,7),  '204',    4,4,4,4,4, null,          null],
  ['Dewasa',           'LIANNA KARTIKAWATI',                              dt(3,7),  '305',    5,5,5,5,5, null,          null],
  ['Dewasa',           'SHANNON ALYCE WALL',                              dt(3,7),  '202',    4,4,4,4,4, null,          'TIDAK KONSUMSI SUSU SAPI'],
  ['Dewasa',           'MAAIKE ANNA HOOGLAND',                            dt(3,7),  '203',    4,4,3,5,4, 'Makan siang', 'SOP NYA KURANG ASIN'],
  ['Dewasa',           'VINCENTIUS LIANTO',                               dt(3,7),  '206',    4,4,4,4,4, 'Makan pagi',  'oatmeal nya dimasak pakai susu bukan pakai air'],
  ['Anak',             'DEWA GEDE DANENDRA ARSYAWIRYA',                   dt(3,8),  '204',    5,5,5,5,5, 'Makan siang', 'Jangan berikan wortel karena dibatasi oleh dokter'],
  ['Dewasa',           'MAAIKE ANNA HOOGLAND',                            dt(3,8),  '203',    5,5,5,5,5, null,          null],
  ['Dewasa',           'MARIEKE ANTJE VISSER',                            dt(3,8),  '307',    4,4,4,4,4, null,          null],
  ['Anak',             'SAKHI FAEYZA RASHAFA NASUTION',                   dt(3,8),  '306',    4,4,4,4,4, null,          null],
  ['Dewasa',           'MARIEKE ANTJE VISSER',                            dt(3,9),  '307',    4,4,4,4,4, null,          'Tidak suka tahu atau soy sauce'],
  ['Anak',             'SAKHI FAEYZA RASHAFA NASUTION',                   dt(3,9),  '306',    4,4,4,4,4, null,          'Anak belum mau makan makanan RS'],
  ['Dewasa',           'DIEGO OBROSOV',                                   dt(3,9),  '208',    5,5,5,5,5, null,          'tidak ada keluhan'],
  ['Anak',             'TRISTAN LYSANDER GOLDAHAUSEN',                    dt(3,9),  '207',    4,4,4,4,4, null,          'pasien tidak suka cream soup. besok akan coba diganti bubur sumsum'],
  ['Dewasa',           'GUSTI AYU AGUNG RIKA MULYASARI',                  dt(3,9),  '202',    5,5,5,5,5, null,          'Makanannya enak, habis untuk saya. Tolong tambahkan garam terpisah untuk jaga-jaga kalau asinnya kurang'],
  ['Dewasa',           'IVANA LARA MELINDA',                              dt(3,9),  '205',    5,5,5,5,5, null,          'Makanannya enak, saya mau tetap bubur dulu'],
  ['Dewasa',           'JUDITH DE BOER',                                  dt(3,9),  '201',    5,5,5,5,5, null,          'All good'],
  ['Dewasa',           'MARIEKE ANTJE VISSER',                            dt(3,10), '307',    4,4,4,4,4, null,          'all good'],
  ['Anak',             'SAKHI FAEYZA RASHAFA NASUTION',                   dt(3,10), '306',    4,4,4,4,4, null,          'Anak saya belum mau makan, hanya snack dan pisangnya saja. Besok mau coba ke mie atau bihun'],
  ['Dewasa',           'DIEGO OBROSOV',                                   dt(3,10), '208',    5,5,5,5,5, null,          null],
  ['Dewasa',           'GUSTI AYU AGUNG RIKA MULYASARI',                  dt(3,10), '202',    5,5,5,5,5, null,          'Makanannya enak'],
  ['Dewasa',           'IVANA LARA MELINDA',                              dt(3,10), '205',    5,5,5,5,5, null,          'Enak, mau tetap bubur dulu'],
  ['Dewasa',           'JUDITH DE BOER',                                  dt(3,10), '201',    5,5,5,5,5, null,          'Good'],
  ['Dewasa',           'YOHANA MAHDITYARA CHRISTRIANA PUTRI',             dt(3,10), '206',    5,5,5,5,5, null,          'Baik semua'],
  ['Anak',             'PUTU DIANDRA AMIYA ARISUANDI',                    dt(3,10), '204',    4,4,4,4,4, null,          'Makanan enak, cuma porsi terlalu sedikit, masih kalah dengan RS BaliMed. Hari ini diberikan saus bbq yg pedas kurang cocok untuk anak. Pasien merasa kurang sehingga dibawakan makanan dari rumah. Buah nya terlalu sedikit'],
  ['Dewasa',           'JUDITH DE BOER',                                  dt(3,12), '201',    5,5,5,5,5, null,          null],
  ['Dewasa',           'LUCINDA ROSE MULDOON',                            dt(3,12), '304',    5,5,5,5,5, null,          null],
  ['Dewasa',           'I KADEK AGUS PRANATHA KESUMA PUTRA',              dt(3,12), '305',    5,5,5,5,5, null,          null],
  ['Dewasa',           'ARDHANA RESWARI MASYKURI',                        dt(3,12), '207',    4,4,4,4,4, null,          'proteinnya kurang, jadi kondisi ibunya perlu makan protein banyak. Ex : ayam goreng lengkuas di kasi 2 porsi'],
  ['Dewasa',           'LISA ANNIE MARIE DUVERGER',                       dt(3,12), '203',    4,4,4,4,4, null,          'Tidak suka jus alpukat tapi klo jus lain aman'],
  ['Anak',             'PUTU DIANDRA AMIYA ARISUANDI',                    dt(3,12), '204',    3,3,3,3,3, null,          'minta protein dan porsi makananya di banyakin. Ayam di kasi banyak dan scramble dikasi susu 2 sendok makan agar lembut (tidak mau pake butter/margarin katanya nggak sehat). Di setiap makan pagi harus ada protein hewani (scramble)'],
  ['Anak',             'PUTU DIANDRA AMIYA ARISUANDI',                    dt(3,13), '204',    4,4,4,4,4, null,          'Menurut pengasuh tidak ada keluhan terkait makanan pasien. Nenek pasien tidak di ruangan hingga sore'],
  ['Dewasa',           'LISA ANNIE MARIE DUVERGER',                       dt(3,13), '203',    5,5,5,5,5, null,          'All good'],
  ['Dewasa',           'I KADEK AGUS PRANATHA KESUMA PUTRA',              dt(3,13), '305',    5,5,5,5,5, null,          'tidak ada keluhan, dan note tertentu'],
  ['Dewasa',           'PENDAMPING BY. NY. LUH GEDE VERA YUNIARI',        dt(3,15), '204',    5,5,5,5,5, null,          null],
  ['Dewasa',           'ANDY PUTRA SURYANTO',                             dt(3,15), '202',    3,3,3,3,3, 'Makan siang', 'Makanan terasa hambar karena diberikan chicken nugget kukus dan tahu kukus'],
  ['Dewasa',           'I GUSTI AYU MADE ICHA ELVAROSA',                  dt(3,17), '201',    5,5,5,5,5, null,          null],
  ['Anak',             'I KADEK KENDRICK PRADIPTA',                       dt(3,17), '307',    4,4,4,4,4, null,          null],
  ['Anak',             'I GUSTI AGUNG ADISTYA LAKSITA MAHARANI KEMALA',   dt(3,20), '306',    5,5,5,5,5, 'Makan siang', 'wortel terlalu keras, anak sulit mengonsumsinya, tidak suka telur, tidak enak (padahal yg dimaksud adalah tempe grill)'],
  ['Anak',             'I GUSTI AGUNG ADISTYA LAKSITA MAHARANI KEMALA',   dt(3,21), '306',    5,5,5,5,5, null,          'Nasi agak kering'],
  ['Anak',             'PUTU RANIA CIPTA AMBARA',                         dt(3,22), '204 A',  5,5,5,5,5, null,          null],
  ['Anak',             'I MADE RAVANDU PUTRA AMBARA',                     dt(3,22), '204 B',  5,5,5,5,5, null,          null],
  ['Anak',             'CAMDEN KENTJANAPUTRA',                            dt(3,22), '307',    5,5,5,5,5, null,          null],
  ['Anak',             'CRESCENCIO KAI SOEGIARTO',                        dt(3,22), '205',    5,5,5,5,5, null,          null],
  ['Anak',             'PUTU RANIA CIPTA AMBARA',                         dt(3,23), '204 A',  4,4,4,4,4, 'Makan siang', 'Tekstur ayam teriyaki agak keras'],
  ['Anak',             'I MADE RAVANDU PUTRA AMBARA',                     dt(3,23), '204 B',  5,5,5,5,5, null,          null],
  ['Anak',             'CAMDEN KENTJANAPUTRA',                            dt(3,23), '307',    5,5,5,5,5, null,          null],
  ['Anak',             'CRESCENCIO KAI SOEGIARTO',                        dt(3,23), '205',    5,5,5,5,5, null,          null],
  ['Pendamping pasien','I PUTU ELEONATA LOUIS',                           dt(3,23), '202',    4,4,4,4,4, null,          null],
  ['Anak',             'PUTU RANIA CIPTA AMBARA',                         dt(3,24), '204 A',  5,5,5,5,5, null,          null],
  ['Anak',             'I MADE RAVANDU PUTRA AMBARA',                     dt(3,24), '204 B',  5,5,5,5,5, 'Makan siang', 'Anak tidak suka mengonsumsi chicken grill'],
  ['Anak',             'CAMDEN KENTJANAPUTRA',                            dt(3,24), '307',    5,5,5,5,5, null,          null],
  ['Pendamping pasien','I PUTU ELEONATA LOUIS',                           dt(3,24), '202',    4,4,4,4,4, 'Makan siang', 'Chicken breaded mayo agak keras karena dingin'],
  ['Dewasa',           'I PUTU GEDE SURYA WIBAWA',                        dt(3,24), '306',    5,5,5,5,5, null,          null],
  ['Pendamping pasien','I PUTU ELEONATA LOUIS',                           dt(3,26), '202',    5,5,5,5,5, null,          null],
  ['Dewasa',           'I GEDE ARTHA SUDIARSANA',                         dt(3,26), '203',    5,5,5,5,5, 'Makan pagi',  'Sop ikan kemarin kurang terasa asin'],
  ['Dewasa',           'NI KADEK ENTANIA SASMITHA',                       dt(3,26), '205',    5,5,5,5,5, null,          null],
  ['Dewasa',           'FREDERIQUE ISABEAU VAN DIJK',                     dt(3,26), '208',    4,4,4,4,4, null,          'Pasien mengatakan tidak suka terlalu banyak makan telur, tidak suka muffin dan tidak suka makan daging terlalu banyak dan hanya menginginkan makanan yang banyak sayur'],
  ['Dewasa',           'I PUTU ELEONATA LOUIS',                           dt(3,27), '202',    4,4,4,4,4, null,          'tidak ada keluhan'],
  ['Dewasa',           'FREDERIQUE ISABEAU VAN DIJK',                     dt(3,27), '208',    4,4,4,4,4, null,          'Makanan yang diberikan terlalu banyak bagi pasien, pasien tidak bisa menghabiskan semua, ia hanya makan sedikit-sedikit, kurang suka dengan rasa mashed potatonya'],
  ['Dewasa',           'NI KADEK ENTANIA SASMITHA',                       dt(3,27), '205',    5,5,5,5,5, null,          'enak'],
  ['Anak',             'NAYANIKA RAE ERLANGGA',                           dt(3,27), '207',    4,4,4,4,4, null,          'tidak ada keluhan, cuma nafsu makan anak saat ini sedang kurang'],
  ['Dewasa',           'I GEDE ADHITIYA YASA',                            dt(3,29), '204',    5,5,5,5,5, null,          'tidak ada keluhan'],
  ['Anak',             'NAYANIKA RAE ERLANGGA',                           dt(3,30), '207',    4,4,4,4,4, null,          'Hari ini anaknya mau makan kalau ada yg berkuah, namun masih mau makan sedikit sedikit'],
  ['Dewasa',           'I GEDE ADHITIYA YASA',                            dt(3,30), '204',    5,5,5,5,5, null,          'Tidak ada keluhan'],
  ['Dewasa',           'KOMANG SRI DESHI ARI PUSPITAWATI',                dt(3,30), '307',    5,5,5,5,5, null,          'Tidak ada keluhan, mau ganti bubur ke nasi lembek'],
  ['Dewasa',           'LADY ATHALIA',                                    dt(3,30), '201',    5,5,5,5,5, null,          'minta nasi karena tadi siang dikasi bubur - post op'],
  ['Dewasa',           'RAHMA AYU',                                       dt(3,30), '306',    4,4,4,4,4, null,          'tidak ada keluhan, sup tahu tadi siang enak'],
  ['Anak',             'I MADE PUTRA JAYA ABADI',                         dt(3,30), '205',    4,4,4,4,4, null,          'belum ada keluhan, baru konsumsi es krim saja'],
]

// ── APRIL 2026 ──────────────────────────────────────────────────────────────
const APRIL: Row[] = [
  ['Dewasa',           'NURUL RAYA IMANIATI',                             dt(4,1),  '202',    5,5,5,5,5, null,          'Makanan disini enak, hanya saja saya tidak bisa konsumsi nasi, ingin ganti karbo ke jenis lain'],
  ['Dewasa',           'SOPHIE CHARLOTTE TAIT',                           dt(4,1),  '203',    4,4,4,4,4, null,          'tidak ada keluhan maupun catatan khusus'],
  ['Dewasa',           'BY NY NI KOMANG ARY RESTYANI',                   dt(4,1),  '207',    4,4,4,4,4, null,          'Tidak ada keluhan'],
  ['Dewasa',           'NURUL RAYA IMANIATI',                             dt(4,2),  '202',    5,5,5,5,5, null,          'tidak ada keluhan, masih sulit konsumsi nasi, lauk oke'],
  ['Dewasa',           'NADYA ASTAWA WANGGO',                             dt(4,2),  '205',    5,5,5,5,5, null,          'makanan enak semua'],
  ['Anak',             'JONATHAN GERASSIMOV',                             dt(4,2),  '305',    5,5,5,5,5, null,          'tidak ada keluhan'],
  ['Anak',             'ANAK AGUNG NGURAH BAGUS DEVANANDRA KUSUMANINGRAT',dt(4,2),  '306',    4,4,4,4,4, null,          'makananya enak semua, cuma porsinya sedikit. Next tidak mau garnish timun, selada, tomat'],
  ['Bayi',             'BY NY NI KOMANG ARY RESTYANI',                   dt(4,2),  '207',    5,5,5,5,5, null,          'tidak ada keluhan'],
  ['Dewasa',           'NURUL RAYA IMANIATI',                             dt(4,3),  '202',    5,5,5,5,5, null,          null],
  ['Dewasa',           'NADYA ASTAWA WANGGO',                             dt(4,3),  '205',    5,5,5,5,5, null,          null],
  ['Dewasa',           'UTAMI NINGSIH',                                   dt(4,3),  '204',    5,5,5,5,5, null,          null],
  ['Dewasa',           'AKIM OZHEGOV',                                    dt(4,3),  '208',    5,5,5,5,5, 'Makan siang', 'Pasien tidak suka mengonsumsi wortel'],
  ['Dewasa',           'MARIIA VERESHCHAGINA',                            dt(4,5),  '204',    5,5,5,5,5, null,          null],
  ['Dewasa',           'RADEN DITA PERMATASARI',                          dt(4,5),  '201',    5,5,5,5,5, null,          null],
  ['Dewasa',           'I GUSTI AYU BERLIAN PRAYANTHI',                   dt(4,5),  '307',    5,5,5,5,5, null,          null],
  // bulanPenilaian APRIL tapi tanggalPenilaian 3/5/2026
  ['Dewasa',           'SINTA NATALIA PAATH',                             dt(3,5),  '202',    5,5,5,5,5, null,          null],
  ['Dewasa',           'I GUSTI AGUNG ISTRI RATIH GRAVITY',               dt(3,5),  '207',    3,3,3,3,3, 'Makan siang', 'AYAM DI MASAK KURANG KERING DAN MASIH ADA BAU AMIS'],
  ['Dewasa',           'SINTA NATALIA PAATH',                             dt(4,6),  '202',    5,5,5,5,5, null,          'makananya enak, coba kurangi tepung'],
  ['Dewasa',           'I GUSTI AGUNG ISTRI RATIH GRAVITY',               dt(4,6),  '207',    4,4,4,4,4, null,          'Saya suka makanannya, tapi yg siang hari ini (chicken grill) agak asin. Pagi ini sy pilih chicken sandwich tapi saya lupa tidak boleh konsumsi yg mentah, jadi sayuran di sandwich saya sisihkan. next garnish tidak perlu dikasi potongan timun/tomat yg mentah'],
  ['Dewasa',           'I GUSTI AYU BERLIAN PRAYANTHI',                   dt(4,6),  '307',    5,5,5,5,5, null,          'Mau tetap diberikan snack jus pepaya, saat ini belum terlalu ingin makan, kebanyakan konsumsi soupnya saja. malam ini mau ganti ke bubur, dan besok pagi mau bubur dan telur rebus saja'],
  ['Anak',             'ROSS MICHAEL WRIGHT',                             dt(4,6),  '206',    4,4,4,4,4, null,          'tidak ada keluhan, anak saya hanya makan sedikit-sedikit, besok pagi mau pulang pagi bisa dikasi roti dan pisang serta almond milk saja'],
  ['Dewasa',           'I GUSTI AGUNG ISTRI RATIH GRAVITY',               dt(4,7),  '207',    4,4,4,4,4, null,          'Rasa makanan di RS kurang berasa, tapi semuanya enak dan bisa dimakan'],
  ['Anak',             'JOANNA CELLINE WIRYAWAN ADI GUNAWAN',             dt(4,7),  '201',    4,4,4,4,4, null,          'MAKANAN TERLALU ASIN, TAPI MASIH BISA DI MAKAN'],
  ['Lansia',           'NI WAYAN GANDI',                                  dt(4,7),  '204',    5,5,5,5,5, null,          null],
  ['Lansia',           'NI WAYAN GANDI',                                  dt(4,8),  '305',    5,5,5,5,5, null,          null],
  ['Anak',             'UMAR ZOIROV',                                     dt(4,8),  '205',    5,5,5,5,5, null,          null],
  ['Lansia',           'THEODORUS HYACINTUS MARIA BELLEMAN',              dt(4,8),  '306',    5,5,5,5,5, null,          null],
  ['Anak',             'UMAR ZOIROV',                                     dt(4,9),  '205',    5,5,5,5,5, null,          'all good, we need more fruit, we will pay for it'],
  ['Anak',             'I PUTU HARSA AGASTYA PIADNYAN',                   dt(4,9),  '203',    5,5,5,5,5, null,          'Anak saya belum mau makan, jika bisa mau request pasta untuk besok'],
  ['Anak',             'I PUTU HARSA AGASTYA PIADNYAN',                   dt(4,10), '203',    5,5,5,5,5, null,          'tidak ada keluhan'],
  ['Dewasa',           'ALESSANDRO ROMANO',                               dt(4,10), '307',    5,5,5,5,5, null,          'everything good! jika kamu ada makanan lebih yang sekiranya akan dibuang, aku bisa memakannya.'],
  ['Dewasa',           'GST. NGURAH BAGUS KADE JOVANKA DINATA',           dt(4,10), '203',    5,5,5,5,5, null,          'tidak ada keluhan, anak saya suka mashed potatonya, saya keep dulu'],
  ['Dewasa',           'ALESSANDRO ROMANO',                               dt(4,11), '307',    5,5,5,5,5, null,          null],
  ['Anak',             'GST. NGURAH BAGUS KADE JOVANKA DINATA',           dt(4,11), '206',    5,5,5,5,5, null,          null],
  ['Anak',             'NI PUTU MIRAH WAHYUNI ANDAYANI',                  dt(4,11), '205',    4,4,4,4,4, null,          null],
  ['Anak',             'GST. NGURAH BAGUS KADE JOVANKA DINATA',           dt(4,12), '206',    5,5,5,5,5, null,          'Ibu pasien mengatakan anak sudah bisa makan dan habis, rasa makanan enak'],
  ['Anak',             'NI PUTU MIRAH WAHYUNI ANDAYANI',                  dt(4,12), '205',    4,4,4,4,4, null,          null],
  ['Pendamping pasien','BY. NY. SOPHIE CHARLOTTE TAIT',                   dt(4,12), '203',    4,4,4,4,4, null,          null],
  ['Anak',             'GST. NGURAH BAGUS KADE JOVANKA DINATA',           dt(4,13), '206',    5,5,5,5,5, null,          'tidak ada keluhan, anak tidak mau pisang lagi minta buah semangka/melon'],
  ['Anak',             'NI PUTU MIRAH WAHYUNI ANDAYANI',                  dt(4,13), '205',    5,5,5,5,5, null,          'tidak ada keluhan, pasien inginkan buah lain seperti jeruk (namun belum tersedia di RS) sudah dijelaskan untuk buah yang tersedia, pasien sudah setuju'],
  ['Anak',             'PUTU MAHAKIRANA NEHA LAVANYA',                    dt(4,14), '203',    5,5,5,5,5, null,          null],
  ['Dewasa',           'LUH AYU GITAVIRA SARASVATI',                      dt(4,14), '202',    5,5,5,5,5, null,          null],
  ['Anak',             'PUTU MAHAKIRANA NEHA LAVANYA',                    dt(4,15), '203',    5,5,5,5,5, null,          'pasien memberikan nilai 5 (sambil tersenyum), tidak ada keluhan'],
  ['Dewasa',           'ANASTASIA VOSKOBOYNIK',                           dt(4,16), '208',    5,5,5,5,5, null,          null],
  ['Dewasa',           'OLESIA SAVELEVA',                                 dt(4,16), '205',    5,5,5,5,5, null,          null],
  ['Anak',             'REVANDRA RAI VERET',                              dt(4,16), '207',    4,4,4,4,4, null,          null],
  ['Anak',             'MADE MAYIRRA KEISHYA CHANDANI',                   dt(4,16), '202',    4,4,4,4,4, null,          null],
  ['Dewasa',           'EVA KURNIA BRATANATA',                            dt(4,16), '204',    5,5,5,5,5, null,          null],
  ['Dewasa',           'ANASTASIA VOSKOBOYNIK',                           dt(4,17), '208',    5,5,5,5,5, null,          null],
  ['Dewasa',           'OLESIA SAVELEVA',                                 dt(4,17), '205',    5,5,5,5,5, null,          null],
  ['Dewasa',           'KRISTINA SAYFULLINA',                             dt(4,17), '206',    5,5,5,5,5, null,          null],
  ['Dewasa',           'KOMANG ADELIA TRISNADEVY',                        dt(4,17), '201',    5,5,5,5,5, null,          null],
  ['Anak',             'FREDERIC HAYDEN SUSANTO',                         dt(4,17), '203 A',  4,4,4,4,4, null,          null],
  ['Anak',             'RICHARDSON HAYDEN SUSANTO',                       dt(4,17), '203 B',  4,4,4,4,4, null,          null],
  ['Anak',             'REVANDRA RAI VERET',                              dt(4,17), '207',    5,5,5,5,5, null,          null],
  ['Dewasa',           'KOMANG ADELIA TRISNADEVY',                        dt(4,19), '204',    4,4,4,4,4, null,          'Ayam siang ini agak keras. Saya mau bubur terus'],
  ['Anak',             'MICHELLE NANDIYA WINATA',                         dt(4,19), '205',    3,3,3,3,3, null,          'Belum nafsu makan, harusnya menu ayam lengkuas tidak disajikan bersama tulangnya karena saya kesulitan untuk memisahkan tulang dan daging (tangan kanan diinfus)'],
  ['Dewasa',           'KOMANG ADELIA TRISNADEVY',                        dt(4,20), '204',    4,4,4,4,4, null,          'Mashed potato di hari pertama seperti ada rasa pedasnya. (sudah dijelaskan oleh gizi bahwa kondiment tidak mengandung cabai atau lada), pasien mengerti'],
  ['Anak',             'MICHELLE NANDIYA WINATA',                         dt(4,20), '205',    4,4,4,4,4, 'Makan siang', 'Penilaian sudah ada kenaikan dari kemarin, creamy chicken mushroom siang ini sedikit hambar'],
  ['Dewasa',           'DENISE GIELEN',                                   dt(4,20), '202',    5,5,5,5,5, null,          'All is perfect'],
  ['Dewasa',           'DILARA SUBASI',                                   dt(4,20), '201',    5,5,5,5,5, null,          'Perfect'],
  ['Dewasa',           'MIKE TROMP',                                      dt(4,20), '306',    5,5,5,5,5, null,          'good'],
  ['Dewasa',           'KOMANG ADELIA TRISNADEVY',                        dt(4,21), '204',    4,4,4,4,4, 'Makan siang', 'Terdapat batu di protein nabati (tempe)'],
  ['Anak',             'MICHELLE NANDIYA WINATA',                         dt(4,21), '205',    4,4,4,4,4, null,          null],
  ['Dewasa',           'DILARA SUBASI',                                   dt(4,21), '201',    5,5,5,5,5, null,          null],
  ['Anak',             'SHAWN EZEKIEL SUBIANTO',                          dt(4,21), '206',    4,4,4,4,4, null,          null],
  ['Dewasa',           'DENISE GIELEN',                                   dt(4,21), '202',    5,5,5,5,5, null,          null],
  ['Anak',             'PANDE PUTU DANADYAKSHA',                          dt(4,22), '205',    5,5,5,5,5, null,          'Tidak ada keluhan'],
  ['Anak',             'SHAWN EZEKIEL SUBIANTO',                          dt(4,22), '206',    4,4,4,4,4, null,          'Tidak ada keluhan hanya saja anak saya belum nafsu makan, mau bubur saja dulu dilanjutkan'],
  ['Anak',             'MICHELLE NANDIYA WINATA',                         dt(4,22), '205',    4,4,4,4,4, null,          'Makan malam kemarin kurang menggugah selera (Ikan grill, agak amis), tapi yg hari ini oke sih'],
  ['Anak',             'SHAWN EZEKIEL SUBIANTO',                          dt(4,23), '206',    4,4,4,4,4, null,          null],
  ['Anak',             'PUTU NARARYA DEVAN SUNARENDRA',                   dt(4,26), '203',    4,4,4,4,4, null,          'Makanan perlu di tingkatkan rasa asinnya'],
  ['Anak',             'MOIRA RAPHAELA LOUIS',                            dt(4,26), '208',    5,5,5,5,5, null,          'Kuah enak, minta dibanyakin kuahnya'],
  ['Dewasa',           'AA NGURAH GEDE NILESWARA UDAYADITYA WARMAN',      dt(4,26), '202',    5,5,5,5,5, null,          null],
  ['Anak',             'JUSTIN ARIENA LOUIS HERMAN',                      dt(4,26), '204',    5,5,5,5,5, 'Makan pagi',  'Nasi agak keras'],
  ['Dewasa',           'JUSTIN ARIENA LOUIS HERMAN',                      dt(4,27), '204',    5,5,5,5,5, null,          'tidak ada, pasien ingin bubur sumsum'],
  ['Dewasa',           'DESYVEN BLANDINA',                                dt(4,27), '207',    4,4,4,4,4, 'Makan siang', 'tidak suka mashed potatonya, selain itu all good'],
  ['Dewasa',           'DESYVEN BLANDINA',                                dt(4,28), '207',    5,5,5,5,5, null,          'Lebih suka menu lokal'],
  ['Anak',             'NI PUTU NAIRA PUSPANDARI',                        dt(4,28), '205',    4,4,4,4,4, null,          'nanti mau ganti ke nasi putih saja'],
  ['Anak',             'NI NYOMAN ADISTHREE B P',                         dt(4,28), '201',    5,5,5,5,5, null,          'Tidak ada keluhan, makanan bisa dihabiskan semua'],
  ['Anak',             'NI NYOMAN ADISTHREE B P',                         dt(4,29), '201',    5,5,5,5,5, null,          null],
  ['Anak',             'VANESSA OLIVIA GOUW',                             dt(4,29), '307',    5,5,5,5,5, null,          null],
  // bulanPenilaian "April" (salah input), tanggalPenilaian di Mei
  ['Dewasa',           'ENDRI PUSPITASARI',                               dt(5,4),  '205',    5,5,5,5,5, null,          'Makanannya enak, saya bisa habiskan'],
  ['Anak',             'ARKA PUTRA PRATAMA',                              dt(5,4),  '203',    5,5,5,5,5, null,          'Ortu: anak saya mau makan makanan disini'],
  ['Anak',             'PUTU RADITA OKA PRADANA',                         dt(5,4),  '206',    5,5,5,5,5, null,          'Tidak ada keluhan'],
  ['Dewasa',           'DINA APRILIA DEWI',                               dt(5,4),  '307',    5,5,5,5,5, null,          'Makanan hari ini tidak ada keluhan, namun yg kemarin kurang garam (ahli gizi sudah menyampaikan bahwa pasien perlu mengurangi konsumsi garam karena tensi tinggi)'],
]

// ── MEI 2026 ────────────────────────────────────────────────────────────────
const MEI: Row[] = [
  ['Dewasa',           'GEMMA INGHLIERI',                                 dt(5,1),  '205',    5,5,5,5,5, null,          null],
  ['Dewasa',           'DEWI SINTA MAHARANI',                             dt(5,1),  '306',    4,4,4,4,4, null,          null],
  ['Dewasa',           'ENDRI PUSPITASARI',                               dt(5,2),  '205',    5,5,5,5,5, 'Makan siang', 'Tekstur ayam keras'],
  ['Dewasa',           'ENDRI PUSPITASARI',                               dt(5,3),  '205',    4,4,4,4,4, null,          null],
  ['Anak',             'ARKA PUTRA PRATAMA',                              dt(5,3),  '203',    4,4,4,4,4, null,          null],
  ['Anak',             'PUTU RADITA OKA PRADANA',                         dt(5,3),  '206',    5,5,5,5,5, null,          null],
  ['Dewasa',           'DINA APRILIA DEWI',                               dt(5,3),  '307',    4,4,4,4,4, null,          null],
  ['Dewasa',           'VANESA FRANSISCA WIYOTO',                         dt(5,3),  '204',    4,4,4,4,4, null,          null],
  ['Anak',             'ARKA PUTRA PRATAMA',                              dt(5,5),  '203',    5,5,5,5,5, null,          null],
  ['Anak',             'NI PUTU ADISTY CASSANDRA NARASHIVA',              dt(5,5),  '307',    5,5,5,5,5, null,          null],
  ['Anak',             'RAFAIZAN UKKASYA MULYADI',                        dt(5,5),  '306',    4,4,4,4,4, 'Makan siang', 'Nasi terlalu lembek'],
  ['Dewasa',           'LISNA ROHMAWATI',                                 dt(5,5),  '202',    5,5,5,5,5, null,          null],
  ['Anak',             'PUTU RADITA OKA PRADANA',                         dt(5,5),  '206',    4,4,4,4,4, 'Makan siang', 'Tempe terlalu berbumbu'],
  ['Anak',             'NI PUTU ADISTY CASSANDRA NARASHIVA',              dt(5,6),  '307',    4,4,4,4,4, null,          null],
  ['Anak',             'RAFAIZAN UKKASYA MULYADI',                        dt(5,6),  '307',    5,5,5,5,5, null,          null],
  ['Dewasa',           'FASEH HULISAN',                                   dt(5,6),  '201 A',  4,4,4,4,4, null,          null],
  ['Anak',             'QIANA DEFA DIVYANISA',                            dt(5,6),  '201 B',  3,3,3,3,3, 'Makan siang', 'Makanan kurang berasa'],
  ['Dewasa',           'MADE MIRNA DEVANI',                               dt(5,6),  '207',    4,4,4,4,4, null,          null],
  ['Dewasa',           'FASEH HULISAN',                                   dt(5,7),  '201 A',  4,4,4,4,4, null,          'sudah oke'],
  ['Anak',             'QIANA DEFA DIVYANISA',                            dt(5,7),  '201 B',  4,4,4,4,4, null,          'hari ini sudah dapat nasi tapi di siang malah dapat bubur saya gak tau kenapa'],
  ['Dewasa',           'MADE MIRNA DEVANI',                               dt(5,7),  '207',    4,4,4,4,4, null,          'Saya tidak suka sayur'],
  ['Dewasa',           'UMI BILQIS NABILAH',                              dt(5,7),  '204',    5,5,5,5,5, null,          'semuanya oke'],
  ['Dewasa',           'NAILATUL HOTIJAH',                                dt(5,7),  '208',    5,5,5,5,5, null,          'tidak ada keluhan'],
  ['Dewasa',           'DR. SEPTIA KURNIATY',                             dt(5,9),  '202',    4,4,4,4,4, null,          null],
  ['Dewasa',           'DR. SEPTIA KURNIATY',                             dt(5,10), '202',    4,4,4,4,4, null,          null],
  ['Dewasa',           'KADEK WIRA ADNYANI',                              dt(5,10), '207',    4,4,4,4,4, null,          null],
  ['Anak',             'ANAK AGUNG AYU KANIA PRAMISWARI',                 dt(5,10), '307',    4,4,4,4,4, null,          'anak sedang tidak nafsu makan'],
  ['Anak',             'ANAK AGUNG AYU KANIA PRAMISWARI',                 dt(5,11), '307',    4,4,4,4,4, null,          'minta buburnya 1/2 porsi saja'],
  ['Dewasa',           'DR. SEPTIA KURNIATY',                             dt(5,12), '202',    4,4,4,4,4, null,          'tidak ada keluhan'],
  ['Dewasa',           'DR. SEPTIA KURNIATY',                             dt(5,12), '202',    5,5,5,5,5, null,          null],
  ['Anak',             'ANAK AGUNG AYU KANIA PRAMISWARI',                 dt(5,12), '307',    5,5,5,5,5, null,          null],
  ['Anak',             'MUHAMMAD RAIS NAUFAL K',                          dt(5,12), '204',    4,4,4,4,4, 'Makan siang', 'Nasi anak keras'],
  ['Dewasa',           'I DEWA GEDE SWI ARTAYASA',                        dt(5,12), '203',    5,5,5,5,5, null,          null],
  ['Dewasa',           'ALEXANDRA MAHESWARI',                             dt(5,12), '306',    4,4,4,4,4, null,          null],
  ['Anak',             'SEAN ANTONIO GUNAWAN',                            dt(5,12), '206',    4,4,4,4,4, 'Makan siang', 'Anak tidak suka nasi lembek'],
  ['Dewasa',           'I DEWA GEDE SWI ARTAYASA',                        dt(5,14), '203',    5,5,5,5,5, null,          null],
  ['Dewasa',           'I DEWA GEDE SWI ARTAYASA',                        dt(5,15), '203',    5,5,5,5,5, null,          null],
  ['Dewasa',           'ALEKSANDR SHANIN',                                dt(5,15), '306',    5,5,5,5,5, null,          'all good'],
  ['Dewasa',           'URAY INDAH KHAIRUNNISA',                          dt(5,15), '307',    4,4,4,4,4, null,          null],
  ['Anak',             'I PUTU KIM SANJI KAZAMA',                         dt(5,15), '202',    5,5,5,5,5, null,          null],
  ['Dewasa',           'URAY INDAH KHAIRUNNISA',                          dt(5,17), '307',    4,4,4,4,4, null,          'Terdapat 2-3x makanan terlihat kering dan tidak ada soup dan 3x makan tidak diberikan sendok sehingga harus meminta ke bawah'],
  ['Anak',             'I PUTU KIM SANJI KAZAMA',                         dt(5,17), '202',    5,5,5,5,5, null,          null],
  ['Anak',             'KAIRA SKY LIEM',                                  dt(5,17), '207',    5,5,5,5,5, null,          null],
  ['Dewasa',           'I NYOMAN SILPA MAHADANA',                         dt(5,17), '208',    4,4,4,4,4, null,          null],
  ['Anak',             'I GEDE THEO ABHISEVA',                            dt(5,17), '201',    4,4,4,4,4, null,          null],
  ['Dewasa',           'RACHAEL ABIGAIL SAVERIA',                         dt(5,17), '206',    5,5,5,5,5, null,          null],
]

async function main() {
  const bulanData: [string, Row[]][] = [
    ['MARET',  MARET],
    ['APRIL',  APRIL],
    ['MEI',    MEI],
  ]

  for (const [bulan, rows] of bulanData) {
    console.log(`🌱 Seeding data ${bulan} 2026...`)
    const result = await prisma.survey.createMany({
      data: rows.map(row => toSurvey(bulan, row)),
    })
    console.log(`✅ ${result.count} data ${bulan} berhasil disimpan`)
  }
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
